PACKAGE_NAME="asus-nb-wmi-ux8407aa"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="asus-nb-wmi"
BUILT_MODULE_LOCATION[0]="src"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make -C src KERNELRELEASE=${kernelver}"
CLEAN="make -C src clean"
AUTOINSTALL="yes"
